### PR TITLE
serial backend refactor, 32u4 USB detection fix

### LINKED ISSUE #162: USB issue with 32u4 builds with latest Arduino versions
There's a problem with how Arduino versions post 1.06 are compiling code for the 'leonardo' 32u4 target that causes the chrome API to fail to detect the 32u4 as a valid USB device. The VID and PID look the same as before, but, for some reason, chrome can't pick it up. Currently, the only work-around is to use Arduino 1.06, but we should probably try to figure out exactly why this is happening.

FYI, this is for hardware type 6, the @DTFUHF deluxe 1W TX...

@mikeller, do you have any experience with the 32u4?

### PR DESCRIPTION
**Pull request by csurf**
this is an overhaul of the 'serial backend', which includes a fix for a USB driver/detection issue affecting the 32u4 boards (HW type 6) on Windows for firmware built with Arduino 1.6+ libs. It also includes a general code layout clean-up / refactor.

*this fixes openLRSng/openLRSng#162

### CODE REVIEW

File: js/serial_manager.js [hunk 1]
```diff
@@ -0,0 +1,590 @@
...
+	var e = err[errID];
+	if(e.msg){
+		console.log(e.msg);
+	}
+	if(e.log){
+		GUI.log(chrome.i18n.getMessage(e.log));
+	}
+};
+serial_manager.prototype.init = function() {
+	var that = this;
```
Comment (mikeller) [inline js/serial_manager.js]: This is a bit odd. `self` is the more commonly used variable name for self references in closures.

File: js/serial_manager.js [hunk 2]
```diff
@@ -0,0 +1,590 @@
...
+		this.check_usb_devices();
+	} else {	
+		this.connect_std();
+	}
+};
+
+serial_manager.prototype.check_usb_devices = function () {
+	var that = this;//
+	chrome.serial.getDevices(function(dev){
+		if(!dev || !dev.length) {console.log('error');that.close();}
```
Comment (mikeller) [inline js/serial_manager.js]: Missing newlines.

File: main.html [hunk 3]
```diff
@@ -27,8 +27,9 @@
         <script type="text/javascript" src="./js/serial.js"></script>
         <script type="text/javascript" src="./js/gui.js"></script>
         <script type="text/javascript" src="./js/port_handler.js"></script>
-        <script type="text/javascript" src="./js/serial_backend.js"></script>
-        <script type="text/javascript" src="./js/usb.js"></script>
+        <!--<script type="text/javascript" src="./js/serial_backend.js"></script>-->
```
Comment (mikeller) [inline main.html]: Does this need to be removed?

File: js/serial_manager.js (hunk 1 above)
Comment (csurf) [reply js/serial_manager.js]: `that` and `self` are the two most common forms I've always seen for storing the reference to the current scope. I usually use that (just a personal preference), but I can change it to self though, not a big deal... will fix.

File: js/serial_manager.js (hunk 2 above)
Comment (csurf) [reply js/serial_manager.js]: oops, forgot to clean that up... it was meant just for testing. will fix...

File: main.html (hunk 3 above)
Comment (csurf) [reply main.html]: another 'oops', will fix...

**Comment by csurf** [comment]
FYI, forgot to mention that this PR also adds support for direct-connection of the RX module. This requires running compatible firmware on the RX with the binary protocol. Will label a corresponding patch/PR on firmware side shortly...

**Comment by mikeller** [comment]
I saw the RX support code, neat. :-D

File: js/serial_manager.js (hunk 1 above)
Comment (mikeller) [reply js/serial_manager.js]: Doing it consistently within a project has value. Thanks.

**Review by mikeller — APPROVED** [review]
